import { readFileSync } from "node:fs";

import { describe, expect, test } from "vite-plus/test";

// The `exports` map is GENERATED by `vp pack` from `pack.entry` in
// vite.config.ts, then committed. That makes it easy to break in two invisible
// ways: hand-edit it (overwritten on the next build) or drop the config entry
// (the subpath quietly disappears from the published package). Both leave a
// green build and a broken `import "@kaitencloud/client/testing"` for adopters.
//
// Reads package.json only — no dist — so this holds in CI before any build.
function readFromRoot(rel: string): string {
  for (const base of ["packages/client/", ""]) {
    try {
      return readFileSync(base + rel, "utf8");
    } catch {
      // try the next candidate
    }
  }
  throw new Error(`not found from cwd: ${rel}`);
}

const pkg = JSON.parse(readFromRoot("package.json")) as {
  types?: string;
  files?: string[];
  exports: Record<string, string | { types?: string; default?: string }>;
};

describe("published package shape", () => {
  test("exposes the ./testing subpath", () => {
    expect(pkg.exports["./testing"]).toBeDefined();
  });

  test("every JS subpath export points at a built .mjs", () => {
    for (const [subpath, value] of Object.entries(pkg.exports)) {
      if (subpath === "./package.json") continue;
      const target = typeof value === "string" ? value : value.default;
      expect(target, `${subpath} should resolve to a built module`).toMatch(/\.mjs$/);
    }
  });

  test("declares a top-level types entrypoint into dist", () => {
    expect(pkg.types).toMatch(/^\.\/dist\/.*\.d\.mts$/);
  });

  // The fixtures ship. An adopter's own test suite needs them as much as this
  // repo's does, and `files: ["dist"]` is what carries them.
  test("dist is published", () => {
    expect(pkg.files).toContain("dist");
  });
});
